### PR TITLE
Tooltip hover policy description

### PR DESCRIPTION
**Pull request by lepidopterane-atsmith**
This is my first draft of the feature requested in [this issue](https://github.com/UConnBGP/IssueBoard/issues/46). Please let me know what you think and if there is anything else this feature needs.

### CODE REVIEW

**Comment by iReynaldo** [comment]
It looks like it almost works, but not quite. I agree that the tooltips are displaying the correct information, but the information is not directly coming from the fetched results.

I noticed in commit 91fc2fca153028988bc675e4d55751563b4d8fd2 `policy-description-list.ts` file has the descriptions hard coded.

I think we would prefer that the descriptions would be dynamic (i.e. the descriptions would come directly from the API, so we don't have to change the frontend code when we want to change the descriptions). 

@c-morris @jfuruness what do you think?

**Comment by lepidopterane-atsmith** [comment]
It looked like there was the start of something like that in the API, but it was incomplete. Given a complete set of blurbs to use, I can reroute this from the API.

**Comment by iReynaldo** [comment]
I'm updating the API now to make the fix.

**Comment by iReynaldo** [comment]
@lepidopterane-atsmith API has been updated to have the correct Policy descriptions.

**Comment by iReynaldo** [comment]
@lepidopterane-atsmith API has been updated to have the correct Policy descriptions.
I'm going to close this request, and you can request another one, after updating.
Thanks!

**Pull request closed without merging**
